/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTextDetectRouteImport } from './routes/_authenticated/text-detect'
import { Route as AuthenticatedPlacesRouteImport } from './routes/_authenticated/places'
import { Route as AuthenticatedGuardianRouteImport } from './routes/_authenticated/guardian'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextDetectRoute = AuthenticatedTextDetectRouteImport.update({
  id: '/text-detect',
  path: '/text-detect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlacesRoute = AuthenticatedPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardianRoute = AuthenticatedGuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/places': typeof AuthenticatedPlacesRoute
  '/text-detect': typeof AuthenticatedTextDetectRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/places': typeof AuthenticatedPlacesRoute
  '/text-detect': typeof AuthenticatedTextDetectRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/guardian': typeof AuthenticatedGuardianRoute
  '/_authenticated/places': typeof AuthenticatedPlacesRoute
  '/_authenticated/text-detect': typeof AuthenticatedTextDetectRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/guardian'
    | '/places'
    | '/text-detect'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contacts'
    | '/guardian'
    | '/places'
    | '/text-detect'
    | '/api/chat'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contacts'
    | '/_authenticated/guardian'
    | '/_authenticated/places'
    | '/_authenticated/text-detect'
    | '/api/chat'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/text-detect': {
      id: '/_authenticated/text-detect'
      path: '/text-detect'
      fullPath: '/text-detect'
      preLoaderRoute: typeof AuthenticatedTextDetectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/places': {
      id: '/_authenticated/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AuthenticatedPlacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardian': {
      id: '/_authenticated/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof AuthenticatedGuardianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedGuardianRoute: typeof AuthenticatedGuardianRoute
  AuthenticatedPlacesRoute: typeof AuthenticatedPlacesRoute
  AuthenticatedTextDetectRoute: typeof AuthenticatedTextDetectRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedGuardianRoute: AuthenticatedGuardianRoute,
  AuthenticatedPlacesRoute: AuthenticatedPlacesRoute,
  AuthenticatedTextDetectRoute: AuthenticatedTextDetectRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
